version: '3'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=Bidding_api.settings
    depends_on:
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    command: celery -A Bidding_api worker -l info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=Bidding_api.settings
    depends_on:
      - redis