# Generated by Django 4.2.16 on 2025-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('current_cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_roas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adjusted_cpc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
