# Generated by Django 5.2.3 on 2025-06-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_productbid_calculated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productbid',
            index=models.Index(fields=['calculated_at', 'product_id'], name='idx_calc_product'),
        ),
    ]
